### ISSUE TITLE
Error: This is not a valid Dash or Xcode docset feed

### ISSUE THREAD

**Issue by iandoesallthethings** [yanick/sveltekit-docset#1]
I'd really love to add this docset to dash, but I've never installed docs from a feed before. I tried copying the url and clicking the link from your site, but it's kicking back an error message. Am I doing something wrong?

<img width="820" alt="Screen Shot 2022-08-02 at 1 01 22 PM" src="https://user-images.githubusercontent.com/15148313/182432444-9825ac4c-62c1-4e07-8bc0-d8f43d5ecc3b.png">

**Comment by iandoesallthethings** [comment]
Oh I just figured it out. Dash wants a link to the xml file, not the tgz. 

I got it to install using `https://raw.githubusercontent.com/yanick/sveltekit-docset/main/sveltekit.xml`.

Might be worth adding that to the readme.

**Comment by yanick** [comment]
Good idea. And I should probably try to update the code. Things... changed a wee bit since I last generated those docs. ^.^
